import { describe, expect, it } from "vitest";
import { renderDockerfile, renderDockerignore } from "../../src/core/dockerfile-model.js";
import type { OdooImageBuild } from "../../src/core/project-recipe.js";

const full: OdooImageBuild = {
  aptPackages: ["libgl1-mesa-dev", "tesseract-ocr"],
  pipPackages: ["requests"],
  pipRequirements: ["backend/requirements.txt"],
  copy: [{ from: "backend/sql-script", to: "/opt/kriss-laure/sql-script" }],
  run: ["playwright install chromium-headless-shell", "ln -s /a /b"],
};

describe("renderDockerfile", () => {
  it("renders FROM, apt, requirement COPY, pip, arbitrary COPY, and drops back to the odoo user", () => {
    const text = renderDockerfile("18.0-20250606", full);
    const lines = text.trimEnd().split("\n");
    expect(lines[0]).toMatch(/^# Generated by odoo-agentic-dev/);
    expect(lines[1]).toBe("FROM odoo:18.0-20250606");
    expect(lines[2]).toBe("USER root");
    expect(text).toContain("COPY backend/requirements.txt /tmp/oad-requirements-0.txt");
    expect(text).toContain("COPY backend/sql-script /opt/kriss-laure/sql-script");
    expect(text).toContain(
      "apt-get install -y --no-install-recommends libgl1-mesa-dev tesseract-ocr",
    );
    expect(text).toContain("rm -rf /var/lib/apt/lists/*");
    expect(text).toContain(
      "RUN python3 -m pip install --break-system-packages --ignore-installed -r /tmp/oad-requirements-0.txt requests",
    );
    expect(lines.at(-1)).toBe("USER odoo");
    const apt = lines.findIndex((l) => l.includes("apt-get install"));
    const requirements = lines.findIndex((l) => l.includes("oad-requirements-0.txt"));
    const pip = lines.findIndex((l) => l.includes("pip install"));
    const copy = lines.findIndex((l) => l.includes("backend/sql-script"));
    expect(apt).toBeLessThan(requirements);
    expect(requirements).toBeLessThan(pip);
    expect(pip).toBeLessThan(copy);
  });

  it("emits raw run steps in order, after arbitrary COPYs and before USER odoo", () => {
    const text = renderDockerfile("18.0", full);
    const lines = text.trimEnd().split("\n");
    const copy = lines.findIndex((l) => l.includes("backend/sql-script"));
    const first = lines.indexOf("RUN playwright install chromium-headless-shell");
    const second = lines.indexOf("RUN ln -s /a /b");
    expect(first).toBeGreaterThan(copy);
    expect(second).toBe(first + 1);
    expect(lines.indexOf("USER odoo")).toBeGreaterThan(second);
  });

  it("omits the apt layer without aptPackages and the pip layer without pip inputs", () => {
    const copyOnly = renderDockerfile("18.0", {
      aptPackages: [],
      pipPackages: [],
      pipRequirements: [],
      copy: [{ from: "scripts", to: "/opt/scripts" }],
      run: [],
    });
    expect(copyOnly).not.toContain("apt-get");
    expect(copyOnly).not.toContain("pip install");
    expect(copyOnly).toContain("COPY scripts /opt/scripts");
  });

  it("is deterministic", () => {
    expect(renderDockerfile("18.0", full)).toBe(renderDockerfile("18.0", full));
  });
});

describe("renderDockerignore", () => {
  it("excludes everything and re-includes exactly the COPY'd sources, deduped", () => {
    const text = renderDockerignore({
      ...full,
      pipRequirements: ["backend/requirements.txt", "./backend/requirements.txt"],
    });
    expect(text).not.toBeNull();
    const lines = text!.trimEnd().split("\n");
    expect(lines[0]).toMatch(/^# Generated by odoo-agentic-dev/);
    expect(lines[1]).toBe("*");
    expect(lines.slice(2)).toEqual(["!backend/requirements.txt", "!backend/sql-script"]);
  });

  it("normalizes ./ prefixes, trailing slashes, and windows separators", () => {
    const text = renderDockerignore({
      aptPackages: [],
      pipPackages: [],
      pipRequirements: [],
      copy: [
        { from: "./scripts/", to: "/opt/scripts" },
        { from: "assets\\fonts", to: "/opt/fonts" },
      ],
      run: [],
    });
    expect(text!.trimEnd().split("\n").slice(2)).toEqual(["!scripts", "!assets/fonts"]);
  });

  it("returns null when a source cannot be allowlisted (full context needed)", () => {
    for (const from of [".", "./", "..", "../shared", "/abs/path"]) {
      expect(
        renderDockerignore({
          aptPackages: [],
          pipPackages: [],
          pipRequirements: [],
          copy: [{ from, to: "/opt/x" }],
          run: [],
        }),
      ).toBeNull();
    }
  });

  it("apt/pip-only builds still get a full exclusion (no COPY reads the context)", () => {
    const text = renderDockerignore({
      aptPackages: ["tesseract-ocr"],
      pipPackages: ["requests"],
      pipRequirements: [],
      copy: [],
      run: [],
    });
    expect(text!.trimEnd().split("\n").slice(1)).toEqual(["*"]);
  });
});
