import { describe, expect, it } from "vitest";
import { renderDockerfile } from "../../src/core/dockerfile-model.js";
import type { OdooImageBuild } from "../../src/core/project-recipe.js";

const full: OdooImageBuild = {
  aptPackages: ["libgl1-mesa-dev", "tesseract-ocr"],
  pipPackages: ["requests"],
  pipRequirements: ["backend/requirements.txt"],
  copy: [{ from: "backend/sql-script", to: "/opt/kriss-laure/sql-script" }],
};

describe("renderDockerfile", () => {
  it("renders FROM, COPYs, one apt layer, one pip layer, and drops back to the odoo user", () => {
    const text = renderDockerfile("18.0-20250606", full);
    const lines = text.trimEnd().split("\n");
    expect(lines[0]).toMatch(/^# Generated by odoo-agentic-dev/);
    expect(lines[1]).toBe("FROM odoo:18.0-20250606");
    expect(lines[2]).toBe("USER root");
    expect(text).toContain("COPY backend/requirements.txt /tmp/oad-requirements-0.txt");
    expect(text).toContain("COPY backend/sql-script /opt/kriss-laure/sql-script");
    expect(text).toContain(
      "apt-get install -y --no-install-recommends libgl1-mesa-dev tesseract-ocr",
    );
    expect(text).toContain("rm -rf /var/lib/apt/lists/*");
    expect(text).toContain(
      "RUN python3 -m pip install --break-system-packages --ignore-installed -r /tmp/oad-requirements-0.txt requests",
    );
    expect(lines.at(-1)).toBe("USER odoo");
  });

  it("omits the apt layer without aptPackages and the pip layer without pip inputs", () => {
    const copyOnly = renderDockerfile("18.0", {
      aptPackages: [],
      pipPackages: [],
      pipRequirements: [],
      copy: [{ from: "scripts", to: "/opt/scripts" }],
    });
    expect(copyOnly).not.toContain("apt-get");
    expect(copyOnly).not.toContain("pip install");
    expect(copyOnly).toContain("COPY scripts /opt/scripts");
  });

  it("is deterministic", () => {
    expect(renderDockerfile("18.0", full)).toBe(renderDockerfile("18.0", full));
  });
});
