import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { isAbsolute, relative, resolve } from "node:path";
import { Console, Effect, Option } from "effect";
import { Argument, Command, Flag } from "effect/unstable/cli";
import { createJiti } from "jiti";
import { EjectError, isRuntimeError, renderError } from "../errors/errors.js";
import type { ConfigLoadError, ConfigValidationError } from "../errors/errors.js";
import { buildComposeModel, renderComposeYaml } from "../core/compose-model.js";
import { renderDockerfile } from "../core/dockerfile-model.js";
import type {
  OdooAgenticDevConfig,
  OdooAgenticDevConfigInput,
  OdooImageBuild,
} from "../core/project-recipe.js";
import type { WorktreeContext } from "../core/worktree-context.js";
import { discoverConfigPath, loadRecipe } from "../config/load-recipe.js";
import { validateConfigInput } from "../config/schema.js";
import { resolveContext } from "./resolve-context.js";

export type EjectTarget = "all" | "dockerfile" | "compose";

export const DEFAULT_DOCKERFILE_OUT = "Dockerfile.odoo";
export const DEFAULT_COMPOSE_OUT = "docker-compose.worktree.yml";

// the CLI version stamped into the ejected Dockerfile header (single source:
// package.json, resolved from both dist/ and src/ — mirrors cli.ts)
const CLI_VERSION: string = (() => {
  try {
    const parsed = JSON.parse(
      readFileSync(new URL("../../package.json", import.meta.url), "utf8"),
    ) as { version: string };
    return parsed.version;
  } catch {
    return "0.0.0";
  }
})();

/** A relative path for display/config (forward slashes, no leading "./"). */
const toRelative = (rootDir: string, target: string): string => {
  const abs = isAbsolute(target) ? target : resolve(rootDir, target);
  const rel = relative(rootDir, abs);
  return rel.length === 0 ? abs : rel.split("\\").join("/");
};

// --- pure renderers ---------------------------------------------------------

const GENERATED_DOCKERFILE_HEADER =
  "# Generated by odoo-agentic-dev from `odoo.build` in the project config — do not edit.";

/**
 * The ejected Dockerfile is byte-identical to the generated one except for the
 * first line: ownership now belongs to the project, so the "do not edit" notice
 * is replaced by a provenance stamp carrying the CLI version it was cut from.
 */
export const ejectedDockerfileHeader = (version: string): string =>
  `# Ejected from odoo-agentic-dev v${version} — this file is yours now.`;

/** Render the ejected Dockerfile: the generated body with the header swapped. */
export const renderEjectedDockerfile = (
  odooVersion: string,
  cliVersion: string,
  build: OdooImageBuild,
): string => {
  const generated = renderDockerfile(odooVersion, build);
  return generated.startsWith(GENERATED_DOCKERFILE_HEADER)
    ? ejectedDockerfileHeader(cliVersion) + generated.slice(GENERATED_DOCKERFILE_HEADER.length)
    : generated;
};

// --- config serialization ---------------------------------------------------

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/** Deterministic JS-object literal: identifier keys unquoted, data only. */
const serializeValue = (value: unknown, indent: number): string => {
  if (value === null) return "null";
  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
    return JSON.stringify(value);
  }
  const pad = "  ".repeat(indent);
  const childPad = "  ".repeat(indent + 1);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const items = value.map((item) => `${childPad}${serializeValue(item, indent + 1)}`);
    return `[\n${items.join(",\n")}\n${pad}]`;
  }
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([, v]) => v !== undefined,
    );
    if (entries.length === 0) return "{}";
    const rendered = entries.map(([key, v]) => {
      const renderedKey = IDENTIFIER.test(key) ? key : JSON.stringify(key);
      return `${childPad}${renderedKey}: ${serializeValue(v, indent + 1)}`;
    });
    return `{\n${rendered.join(",\n")}\n${pad}}`;
  }
  return JSON.stringify(String(value));
};

/** Regenerate a complete config file from a validated input object. */
export const serializeConfigFile = (input: OdooAgenticDevConfigInput): string =>
  `import { defineConfig } from "@basaltbytes/odoo-agentic-dev";\n\nexport default defineConfig(${serializeValue(
    input,
    0,
  )});\n`;

/**
 * Whether the source contains `//` or `/*` OUTSIDE string/template literals.
 * URLs like "http://x" inside strings do not count as comments.
 */
export const hasComments = (source: string): boolean => {
  let index = 0;
  const length = source.length;
  while (index < length) {
    const char = source[index];
    if (char === '"' || char === "'" || char === "`") {
      const quote = char;
      index += 1;
      while (index < length && source[index] !== quote) {
        if (source[index] === "\\") index += 1;
        index += 1;
      }
      index += 1;
      continue;
    }
    if (char === "/" && (source[index + 1] === "/" || source[index + 1] === "*")) {
      return true;
    }
    index += 1;
  }
  return false;
};

// --- config patch / mutation ------------------------------------------------

export type EjectChanges = {
  /** config-relative compose file path, when compose was ejected */
  readonly composeFile?: string;
  /** config-relative dockerfile path, when the dockerfile was ejected */
  readonly dockerfileFile?: string;
};

/** Apply ejected-file references to a validated input object (immutably). */
export const applyEjectToInput = (
  input: OdooAgenticDevConfigInput,
  changes: EjectChanges,
): OdooAgenticDevConfigInput => {
  const odoo: Record<string, unknown> = { ...input.odoo };
  if (changes.dockerfileFile !== undefined) {
    // dockerfile and build are mutually exclusive — replace the build block
    delete odoo["build"];
    odoo["dockerfile"] = changes.dockerfileFile;
  }
  const next: Record<string, unknown> = { ...input, odoo };
  if (changes.composeFile !== undefined) {
    next["compose"] = { ...input.compose, file: changes.composeFile };
  }
  return next as OdooAgenticDevConfigInput;
};

/** Human-readable, ready-to-apply patch describing the exact config edits. */
export const buildConfigPatch = (changes: EjectChanges): string => {
  const lines: Array<string> = ["Apply this patch to odoo-agentic-dev.config.ts:"];
  if (changes.composeFile !== undefined) {
    lines.push(
      "",
      "  add at the top level:",
      `    compose: { file: ${JSON.stringify(changes.composeFile)} },`,
    );
  }
  if (changes.dockerfileFile !== undefined) {
    lines.push(
      "",
      "  inside odoo, REPLACE the `build: { ... }` block with:",
      `    dockerfile: ${JSON.stringify(changes.dockerfileFile)},`,
    );
  }
  return lines.join("\n");
};

// --- the eject flow ---------------------------------------------------------

export type EjectResult = {
  readonly written: ReadonlyArray<string>;
  readonly configPatch: string;
  readonly configWritten: boolean;
  /** human notes (e.g. stock image: compose-only eject) */
  readonly notes: ReadonlyArray<string>;
};

const failEject = (reason: string): Effect.Effect<never, EjectError> =>
  Effect.fail(new EjectError({ reason }));

const tryWrite = (path: string, content: string): Effect.Effect<void, EjectError> =>
  Effect.try({
    try: () => writeFileSync(path, content),
    catch: (cause) => new EjectError({ reason: `could not write ${path}: ${String(cause)}` }),
  });

// jiti for re-importing the config input during --write-config (the loader keeps
// its own jiti instance private; eject needs the raw input object back).
// moduleCache:false: we read the config, REWRITE it, and the loader re-imports
// the same path for round-trip proof — a shared module cache would hand the
// loader back the pre-rewrite module, so eject's jiti must never populate it.
const ejectJiti = createJiti(import.meta.url, {
  interopDefault: true,
  moduleCache: false,
  alias: {
    "@basaltbytes/odoo-agentic-dev": (() => {
      for (const candidate of ["../index.js", "../index.ts"]) {
        const path = new URL(candidate, import.meta.url);
        if (existsSync(path)) return path.pathname;
      }
      return "@basaltbytes/odoo-agentic-dev";
    })(),
  },
});

const loadConfigInput = (
  path: string,
): Effect.Effect<OdooAgenticDevConfigInput, ConfigValidationError | EjectError> =>
  Effect.tryPromise({
    try: () => ejectJiti.import(path, { default: true }),
    catch: (cause) =>
      new EjectError({ reason: `could not re-import config ${path}: ${String(cause)}` }),
  }).pipe(Effect.flatMap(validateConfigInput));

export type PerformEjectOptions = {
  readonly recipe: OdooAgenticDevConfig;
  readonly ctx: WorktreeContext;
  readonly rootDir: string;
  readonly target: EjectTarget;
  readonly dockerfileOut: string;
  readonly composeOut: string;
  readonly force: boolean;
  readonly writeConfig: boolean;
  readonly configFlag: string | undefined;
};

/**
 * Convert generated infra into project-owned files: render the portable compose
 * model and (optionally) the ejected Dockerfile, write them as plain files, and
 * either leave a config patch or regenerate the config in place.
 */
export const performEject = (
  options: PerformEjectOptions,
): Effect.Effect<EjectResult, EjectError | ConfigLoadError | ConfigValidationError> =>
  Effect.gen(function* () {
    const { ctx, force, recipe, rootDir, target } = options;
    const dockerfileAbs = isAbsolute(options.dockerfileOut)
      ? options.dockerfileOut
      : resolve(rootDir, options.dockerfileOut);
    const composeAbs = isAbsolute(options.composeOut)
      ? options.composeOut
      : resolve(rootDir, options.composeOut);
    const dockerfileRel = toRelative(rootDir, dockerfileAbs);
    const composeRel = toRelative(rootDir, composeAbs);

    const wantDockerfile = target === "all" || target === "dockerfile";
    const wantCompose = target === "all" || target === "compose";
    const notes: Array<string> = [];

    // A stock image (no build, no hand-written dockerfile) has nothing to eject.
    const canEjectDockerfile = recipe.odoo.build !== null;
    if (target === "dockerfile") {
      if (recipe.odoo.dockerfile !== null) {
        return yield* failEject(
          `the Dockerfile is already ejected / hand-written at ${recipe.odoo.dockerfile} (odoo.dockerfile); nothing to do`,
        );
      }
      if (!canEjectDockerfile) {
        return yield* failEject(
          "there is no Dockerfile to eject: the config uses the stock odoo image. Add an `odoo.build` block first, or eject only the compose file.",
        );
      }
    }
    if (target === "all" && recipe.odoo.dockerfile !== null) {
      notes.push(
        `odoo.dockerfile is already set (${recipe.odoo.dockerfile}); ejecting the compose file only.`,
      );
    }
    if (target === "all" && !canEjectDockerfile && recipe.odoo.dockerfile === null) {
      notes.push(
        "no odoo.build/dockerfile in the config (stock image); ejecting the compose file only.",
      );
    }

    const ejectDockerfileNow =
      wantDockerfile && canEjectDockerfile && recipe.odoo.dockerfile === null;

    // Collision check across every file we will write (before writing any).
    const planned: Array<string> = [];
    if (ejectDockerfileNow) planned.push(dockerfileAbs);
    if (wantCompose) planned.push(composeAbs);
    const conflicts = planned.filter((path) => existsSync(path));
    if (conflicts.length > 0 && !force) {
      return yield* failEject(
        `refusing to overwrite existing file(s) without --force: ${conflicts
          .map((path) => toRelative(rootDir, path))
          .join(", ")}`,
      );
    }

    const written: Array<string> = [];
    const changes: { dockerfileFile?: string; composeFile?: string } = {};

    if (ejectDockerfileNow) {
      const dockerfile = renderEjectedDockerfile(
        recipe.odoo.version,
        CLI_VERSION,
        recipe.odoo.build as OdooImageBuild,
      );
      yield* tryWrite(dockerfileAbs, dockerfile);
      written.push(dockerfileRel);
      changes.dockerfileFile = dockerfileRel;
    }

    if (wantCompose) {
      // point build.dockerfile at the ejected file when both are ejected,
      // else let the model fall back to the existing config value.
      const model = buildComposeModel(recipe, ctx, {
        portable: true,
        ...(ejectDockerfileNow ? { dockerfilePath: dockerfileRel } : {}),
      });
      yield* tryWrite(composeAbs, renderComposeYaml(model));
      written.push(composeRel);
      changes.composeFile = composeRel;
    }

    const configPatch = buildConfigPatch(changes);

    let configWritten = false;
    if (options.writeConfig) {
      const path = yield* options.configFlag !== undefined
        ? Effect.succeed(
            isAbsolute(options.configFlag)
              ? options.configFlag
              : resolve(rootDir, options.configFlag),
          )
        : discoverConfigPath(rootDir).pipe(
            Effect.flatMap((found) =>
              found === undefined
                ? failEject(
                    "could not find a config file to rewrite with --write-config; pass --config",
                  )
                : Effect.succeed(found),
            ),
          );
      const source = yield* Effect.try({
        try: () => readFileSync(path, "utf8"),
        catch: (cause) =>
          new EjectError({ reason: `could not read config ${path}: ${String(cause)}` }),
      });
      if (hasComments(source) && !force) {
        return yield* failEject(
          `--write-config would discard comments in ${toRelative(rootDir, path)}; re-run with --force to overwrite, or apply the printed patch by hand`,
        );
      }
      const input = yield* loadConfigInput(path);
      const nextInput = applyEjectToInput(input, changes);
      yield* tryWrite(path, serializeConfigFile(nextInput));
      // prove the regenerated file re-loads, re-validates, and re-normalizes
      yield* loadRecipe({ cwd: rootDir, explicitPath: path, env: process.env }).pipe(
        Effect.mapError(
          (error) =>
            new EjectError({
              reason: `the regenerated config did not round-trip: ${
                isRuntimeError(error) ? renderError(error) : String(error)
              }`,
            }),
        ),
      );
      configWritten = true;
    }

    return { written, configPatch, configWritten, notes };
  });

// --- command ----------------------------------------------------------------

/** The success payload printed (as one line) to stdout in `--json` mode. */
export const renderEjectJson = (result: EjectResult): string =>
  JSON.stringify({
    ok: true,
    command: "eject",
    written: result.written,
    configPatch: result.configPatch,
    configWritten: result.configWritten,
  });

/** The failure payload printed (as one line) to stdout in `--json` mode. */
export const renderEjectErrorJson = (error: {
  readonly _tag: string;
  readonly message: string;
}): string =>
  JSON.stringify({
    ok: false,
    command: "eject",
    error: { tag: error._tag, message: error.message },
  });

const parseTarget = (raw: string | undefined): Effect.Effect<EjectTarget, EjectError> =>
  raw === undefined || raw === "all"
    ? Effect.succeed<EjectTarget>("all")
    : raw === "dockerfile" || raw === "compose"
      ? Effect.succeed<EjectTarget>(raw)
      : failEject(`unknown eject target "${raw}" (expected: all, dockerfile, or compose)`);

export const ejectCommand = Command.make(
  "eject",
  {
    target: Argument.string("target").pipe(
      Argument.optional,
      Argument.withDescription("all (default), dockerfile, or compose"),
    ),
    dockerfileOut: Flag.string("dockerfile-out").pipe(
      Flag.optional,
      Flag.withDescription(`ejected Dockerfile path (default ${DEFAULT_DOCKERFILE_OUT})`),
    ),
    composeOut: Flag.string("compose-out").pipe(
      Flag.optional,
      Flag.withDescription(`ejected compose path (default ${DEFAULT_COMPOSE_OUT})`),
    ),
    force: Flag.boolean("force").pipe(
      Flag.withDescription("overwrite existing files / commented config"),
    ),
    writeConfig: Flag.boolean("write-config").pipe(
      Flag.withDescription("rewrite the config in place (comments are lost)"),
    ),
    json: Flag.boolean("json").pipe(Flag.withDescription("print machine-readable JSON")),
    config: Flag.string("config").pipe(
      Flag.optional,
      Flag.withDescription("explicit config file path"),
    ),
  },
  (flags) =>
    Effect.gen(function* () {
      const json = flags.json;
      const program = Effect.gen(function* () {
        const target = yield* parseTarget(Option.getOrUndefined(flags.target));
        const { ctx, recipe } = yield* resolveContext(flags.config);
        const result = yield* performEject({
          recipe,
          ctx,
          rootDir: ctx.rootDir,
          target,
          dockerfileOut: Option.getOrUndefined(flags.dockerfileOut) ?? DEFAULT_DOCKERFILE_OUT,
          composeOut: Option.getOrUndefined(flags.composeOut) ?? DEFAULT_COMPOSE_OUT,
          force: flags.force,
          writeConfig: flags.writeConfig,
          configFlag: Option.getOrUndefined(flags.config),
        });

        if (json) {
          // human output to stderr; stdout is exactly one JSON object
          for (const note of result.notes) yield* Console.error(note);
          for (const path of result.written) yield* Console.error(`wrote ${path}`);
          yield* Console.error(
            result.configWritten
              ? "rewrote the config in place (comments, if any, were lost)"
              : result.configPatch,
          );
          yield* Effect.sync(() => process.stdout.write(`${renderEjectJson(result)}\n`));
          return;
        }

        for (const note of result.notes) yield* Console.log(note);
        for (const path of result.written) yield* Console.log(`wrote ${path}`);
        if (result.configWritten) {
          yield* Console.log("rewrote the config in place (comments, if any, were lost).");
        } else {
          yield* Console.log("");
          yield* Console.log(result.configPatch);
        }
      });

      // in JSON mode, typed failures still emit one JSON object on stdout
      return yield* json
        ? program.pipe(
            Effect.catch((error) =>
              Effect.gen(function* () {
                if (isRuntimeError(error)) yield* Console.error(renderError(error));
                yield* Effect.sync(() => process.stdout.write(`${renderEjectErrorJson(error)}\n`));
                yield* Effect.sync(() => {
                  process.exitCode = 1;
                });
              }),
            ),
          )
        : program;
    }),
).pipe(Command.withDescription("write the Dockerfile/compose file into the repo and own them"));
