import type { OdooImageBuild } from "./project-recipe.js";

export const GENERATED_DOCKERFILE_RELATIVE_PATH = ".odoo-agentic-dev/Dockerfile.generated";

const requirementsTarget = (index: number): string => `/tmp/oad-requirements-${index}.txt`;

/**
 * Deterministic Dockerfile from `odoo.build`: FROM the official image, COPY
 * declared files and requirements, one apt layer, one pip layer, back to the
 * odoo user. Lists render in declaration order — same config, same bytes.
 */
export const renderDockerfile = (version: string, build: OdooImageBuild): string => {
  const lines: Array<string> = [
    "# Generated by odoo-agentic-dev from `odoo.build` in the project config — do not edit.",
    `FROM odoo:${version}`,
    "USER root",
  ];

  build.pipRequirements.forEach((file, index) => {
    lines.push(`COPY ${file} ${requirementsTarget(index)}`);
  });
  for (const entry of build.copy) {
    lines.push(`COPY ${entry.from} ${entry.to}`);
  }

  if (build.aptPackages.length > 0) {
    lines.push(
      "RUN apt-get update \\",
      `    && apt-get install -y --no-install-recommends ${build.aptPackages.join(" ")} \\`,
      "    && rm -rf /var/lib/apt/lists/*",
    );
  }

  const pipArgs = [
    ...build.pipRequirements.map((_, index) => `-r ${requirementsTarget(index)}`),
    ...build.pipPackages,
  ];
  if (pipArgs.length > 0) {
    // --break-system-packages: the official image's python is Debian-managed (PEP 668)
    lines.push(
      `RUN python3 -m pip install --break-system-packages --ignore-installed ${pipArgs.join(" ")}`,
    );
  }

  lines.push("USER odoo");
  return lines.join("\n") + "\n";
};
